package zm.mu.ict361lab.data.remote;

import java.util.List;

/**
 * The wire format, exactly as docs/api_contract.md describes it.
 *
 * Field names match the JSON keys, so Gson needs no annotations. Keep them in
 * step with the contract: this file and that document are the same agreement
 * written twice.
 */
public final class Dtos {
    private Dtos() {}

    /* ── auth ── */

    public static class LoginRequest {
        public String email;
        public String password;
        public LoginRequest(String email, String password) {
            this.email = email; this.password = password;
        }
    }

    public static class RegisterRequest {
        public String claim_code;
        public String student_number;
        public String name;
        public String password;
        public RegisterRequest(String claimCode, String studentNumber, String name, String password) {
            this.claim_code = claimCode;
            this.student_number = studentNumber;
            this.name = name;
            this.password = password;
        }
    }

    public static class AuthResponse {
        public String token;
        public String role;
        public String student_id;
    }

    /* ── students ── */

    public static class StudentDto {
        public String student_id;
        public String student_number;
        public String name;
        public int version;
        public Integer group_id;
        public Integer program_id;
        public String program_code;
        public String group_label;
        public String updated_at;
        public boolean is_deleted;
        /** Present only for a lecturer — the student who issues it never sees it. */
        public String claim_code;
    }

    public static class MeDto extends StudentDto {
        public int group_count;
        public Integer group_capacity;
    }

    /** GET /students is paginated: the items live under "items". */
    public static class PageDto {
        public int page;
        public int size;
        public int total;
        public int pages;
        public List<StudentDto> items;
    }

    public static class CreateStudentRequest {
        public String student_number;
        public String name;
        public Integer program_id;
        public CreateStudentRequest(String number, String name, Integer programId) {
            this.student_number = number; this.name = name; this.program_id = programId;
        }
    }

    public static class CreateStudentResponse {
        public String student_id;
        public String claim_code;
    }

    public static class PatchStudentRequest {
        public String name;
        public Integer program_id;
        public int version;
        public String student_number;   // lecturer-only number correction; omit otherwise
        public PatchStudentRequest(String name, Integer programId, int version) {
            this.name = name; this.program_id = programId; this.version = version;
        }
    }

    public static class AssignRequest {
        public Integer group_id;        // null unassigns
        public AssignRequest(Integer groupId) { this.group_id = groupId; }
    }

    public static class NumberCorrectionRequest {
        public String requested_number;
        public NumberCorrectionRequest(String number) { this.requested_number = number; }
    }

    public static class SimpleResponse {
        public boolean success;
        public Integer new_version;
        public Integer group_id;
        public Integer previous_group_id;
        public String group_label;
        public String status;
        public String correction_id;
    }

    /* ── programmes: stored reference data ── */

    public static class ProgrammeDto {
        public int program_id;
        public String code;
    }

    public static class ProgrammesResponse {
        public List<ProgrammeDto> programmes;
    }

    /* ── groups ── */

    public static class GroupDto {
        public int group_id;
        public String label;
        public int capacity;
        public int members;
        public int places_left;
        public boolean full;
    }

    public static class GroupsResponse {
        public List<GroupDto> groups;
        public int unassigned;
    }

    /* ── sync ── */

    /**
     * One payload shape for all four operation types. student_id is always
     * present and is generated by the PHONE for a CREATE, so a student created
     * offline keeps the same identity when it reaches the server — which is
     * what lets a create, then an edit, then a delete of the same student
     * replay in order.
     */
    public static class SyncPayload {
        public String student_id;
        public String student_number;   // CREATE only
        public String name;             // CREATE, UPDATE
        public Integer program_id;      // CREATE, UPDATE
        public Integer group_id;        // ASSIGN
    }

    public static class SyncRequest {
        public String operation_id;
        public String type;
        public SyncPayload payload;
        public int base_version;
    }

    public static class SyncResponse {
        public boolean success;
        public Integer new_version;
        public Integer group_id;
        public Integer previous_group_id;
        public String student_id;
        public String claim_code;       // CREATE: the code the student registers with
        public Boolean deleted;
        public Boolean already_deleted;
    }

    public static class DeletionMarker {
        public String student_id;
        public String deleted_at;
        public int version;
    }

    public static class ChangesResponse {
        public String server_time;
        public List<StudentDto> updates;
        public List<DeletionMarker> deletions;
    }

    /* ── errors ── */

    /** Every failure the server returns has this shape. */
    public static class ErrorDto {
        public String error;
        public Integer current_version;
        public Integer previous_group_id;
        public String correction_id;
        /**
         * On a CONFLICT the server sends the record as it now stands, so the
         * review screen can show the user both versions rather than just
         * telling them something changed.
         */
        public StudentDto current;
    }
}
